# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Scy's Blog
subtitle: 'For Devotion,Keep Passion'
description: "Scy's Blog"
keywords: scy, blog, life
author: Scy
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://scy-six.github.io
permalink: :year/:month/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts 修改创建的默认文件名称
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true    #文章图片相对路径
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: 您的博客索引页的根路径。.(default = '')
# per_page: 每页显示的帖子。(0 =禁用分页). 
# order_by:文章的顺序。(默认按日期降序排序) (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8   #首页文章个数
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10  # 归档文章数
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:scy-six/scy-six.github.io.git
    # gitee: https://gitee.com/scy-six/scy-six.git
    # github: git@github.com:scy-six/scy-six.github.io.git
  branch: main

# 自加
encrypt:
  enable: true    #文章加密

# Ice Kano Plus_in
# Hexo Github Canlendar
# Author: Ice Kano
# Modify: Lete乐特
githubcalendar:
  enable: false
  enable_page: /  # / 代表主页。/me/ 代表自我介绍页等等
  user: scy-six    #你的 github 或者 gitee 用户名
  layout:
    type: class
    name: recent-posts
    index: 0
  githubcalendar_html: '<div class="recent-post-item" style="width:100%;height:auto;padding:10px;"><div id="github_loading" style="width:10%;height:100%;margin:0 auto;display: block"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 50 50" style="enable-background:new 0 0 50 50" xml:space="preserve"><path fill="#d0d0d0" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z" transform="rotate(275.098 25 25)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.6s" repeatCount="indefinite"></animateTransform></path></svg></div><div id="github_container"></div></div>'
  pc_minheight: 280px
  mobile_minheight: 0px
  color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']"
  api: https://python-github-calendar-api.vercel.app/api
  # api: https://python-gitee-calendar-api.vercel.app/api
  calendar_js: https://cdn.jsdelivr.net/gh/Zfour/hexo-github-calendar@1.21/hexo_githubcalendar.js
  plus_style: ""

# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面 根目录就填’/‘,分类页面就填’/categories/‘。若要应用于所有页面，就填’all’，默认为’/‘
  layout: # 挂载容器类型
    type: class
    name: recent-posts
    index: 0
  column: odd # odd：3列 | even：4列
  row: 2 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr: 生灵
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover1.webp
    - descr: 生活
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover2.webp
    - descr: 工作
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover3.webp
    - descr: 文摘
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover4.webp
    - descr: Hexo
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover5.webp
    - descr: 诗记
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover6.webp
    - descr: 旅行
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover4.webp
    - descr: 电脑
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover5.webp
    - descr: 未分类
      cover: https://npm.elemecdn.com/akilar-candyassets/image/cover6.webp
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

#添加emoji表情支持
githubEmojis: 
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

#中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

#哔哩哔哩番剧页面 hexo bangumi -u获取数据更新
bangumi:
  enable: true 
  vmid: 447363686             #哔哩哔哩番剧页面的 vmid(uid)
  title: '追番列表'            #该页面的标题
  quote:      #写在页面开头的一段话，支持 html 语法
  - '生命不息，追番不止！<br/>
甲铁城的卡巴内瑞<br/>
无职转生<br/>
魔王学院的<br/>
回复术士的重启人生<br/>
末日时在做什么?有没有空?可以来拯救吗?<br/>

'
  show: 1                     #初始显示页面：0: 想看 , 1: 在看 , 2: 看过，默认为 1
  loading: '/img/JZ2.gif'     #图片加载完成前的 loading 图片

#本地搜索
# search:
#   path: search.xml
#   field: post
#   content: true
#   format: html

# 统计图表，支持发布文章统计、发布日历、Top标签统计、分类统计、分类雷达。
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # 是否启用功能
  postsChart:
    title: 文章发布统计 # 设置文章发布统计的标题，默认为空
    interval: 1 # 横坐标间隔
  tagsChart:
    title: Top 10 标签统计 # 设置标签统计的标题，默认为空
    interval: 0 # 横坐标间隔
  postsCalendar_title: 文章发布日历 # 设置发布日历的标题，默认为空
  categoriesChart_title: # 设置分类统计的标题，默认为空
  categoriesRadar_title: # 设置分类雷达的标题，默认为空
+ echarts_CDN: # https://lib.baomitu.com/echarts/4.7.0/echarts.min.js